/* PIGEON FLUID — edit this file first. */
window.FLUID_CONFIG = {
  SIM_RESOLUTION: 128,
  PRESSURE_ITERATIONS: 18,
  FORCE: 520,
  SPLAT_RADIUS: 0.018,
  VELOCITY_DISSIPATION: 0.992,
  DYE_DISSIPATION: 0.986,
  COLOR_SLOW: "#7192AD",
  COLOR_FAST: "#97c0e0",
  HIGHLIGHT: "#e3fcff",
  HIGHLIGHT_AMOUNT: 0.12,
  DYE_AMOUNT: 1.35,
  BACKGROUND: "#2e2c29",
  HOVER_INTERACTION: true,
  IDLE_MOTION: true,
  IDLE_INTERVAL_MS: 2200,
  IDLE_FORCE: 0.32,
  HIDE_HINT_ON_INTERACTION: true
};
